# Generated by Django 4.0.4 on 2022-05-24 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=20, verbose_name='Sender')),
                ('recipient', models.CharField(max_length=20, verbose_name='Recipient')),
                ('topic', models.CharField(max_length=200, verbose_name='Topic')),
                ('text', models.TextField(verbose_name='Text')),
                ('date', models.DateTimeField(verbose_name='Date')),
            ],
        ),
    ]
