# Generated by Django 4.0.4 on 2022-05-31 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_id', models.IntegerField(verbose_name='Sender')),
                ('recipient_id', models.IntegerField(verbose_name='Recipient')),
                ('topic', models.CharField(max_length=20, verbose_name='Topic')),
                ('text', models.TextField(verbose_name='Text')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('is_deleted', models.BooleanField(verbose_name='IsDeleted')),
            ],
            options={
                'verbose_name': 'Email',
                'verbose_name_plural': 'Emails',
                'ordering': ['-date'],
            },
        ),
    ]
